const jobData = [
  {
    img: "https://brandemia.org/contenido/subidas/2022/11/tipografia-y-paleta-de-color.png",
    company: "Amazon",
    day: "5 days ago",
    title: "Senior UI/UX Designer",
    spec1: "Part-Time",
    spec2: "Senior Level",
    salary: "$120/hr",
    location: "San Franscisco, CA",
  },
  {
    img: "https://static.vecteezy.com/system/resources/previews/011/598/471/original/google-logo-icon-illustration-free-vector.jpg",
    company: "Microsoft",
    day: "30 days ago",
    title: "Graphic Designer",
    spec1: "Full-Time",
    spec2: "Flexible",
    salary: "$150-200k",
    location: "Mountain View, CA",
  },
  {
    img: "https://static.vecteezy.com/system/resources/previews/012/660/867/original/dribbble-logo-on-transparent-isolated-background-free-vector.jpg",
    company: "Dribbble",
    day: "18 days ago",
    title: "Senior Motion Designer",
    spec1: "Contract",
    spec2: "Remote",
    salary: "$85/hr",
    location: "San Franscisco, CA",
  },
  {
    img: "https://seekvectors.com/files/download/Meta-01.jpg",
    company: "Meta",
    day: "3 months ago",
    title: "UX Designer",
    spec1: "Full Time",
    spec2: "In office",
    salary: "$200-250k",
    location: "New York, NY",
  },
  {
    img: "https://tse1.mm.bing.net/th/id/OIP.3Hp8iRmblKVcbBgTSDXfRAHaE8?pid=Api&P=0&h=180",
    company: "Airbnb",
    day: "1 days ago",
    title: "Junior UI/UX Designer",
    spec1: "Contract",
    spec2: "Remote",
    salary: "$100/hr",
    location: "San Franscisco, CA",
  },
  {
    img: "https://applescoop.org/image/story/76316045115487008-10311484136811093.jpeg",
    company: "Apple",
    day: "6 days ago",
    title: "Graphic Designer",
    spec1: "Full-Time",
    spec2: "Flexible",
    salary: "$85-120k",
    location: "Cupertino, CA",
  },
];


export default jobData;